import chalk from 'chalk'

export function formatForTerminal(guide, repoName) {
  const divider = chalk.dim('─'.repeat(72))
  const header = [
    '',
    chalk.bold.yellow('  claude-onboard'),
    chalk.dim(`  Onboarding guide for: ${chalk.white(repoName)}`),
    '',
    divider,
    '',
  ].join('\n')

  const formatted = guide
    .split('\n')
    .map(line => {
      // H1 headers
      if (/^# /.test(line)) {
        return '\n' + chalk.bold.white(line.replace(/^# /, '  ')) + '\n'
      }
      // H2 headers
      if (/^## /.test(line)) {
        return chalk.bold.cyan(line.replace(/^## /, '  '))
      }
      // H3 headers
      if (/^### /.test(line)) {
        return chalk.bold(line.replace(/^### /, '    '))
      }
      // Numbered list items
      if (/^\d+\. /.test(line)) {
        return '  ' + chalk.yellow(line.match(/^\d+\./)[0]) + ' ' + line.replace(/^\d+\. /, '')
      }
      // Bullet points
      if (/^[-*] /.test(line)) {
        return '  ' + chalk.dim('•') + ' ' + line.replace(/^[-*] /, '')
      }
      // Code blocks — pass through
      if (/^```/.test(line)) {
        return chalk.dim(line)
      }
      // Table rows
      if (/^\|/.test(line)) {
        return chalk.dim('  ') + chalk.white(line)
      }
      // Bold text inline
      const withBold = line.replace(/\*\*(.+?)\*\*/g, (_, m) => chalk.bold(m))
      // Inline code
      const withCode = withBold.replace(/`(.+?)`/g, (_, m) => chalk.bgHex('#1a1a1a').white(` ${m} `))

      return '  ' + withCode
    })
    .join('\n')

  const footer = [
    '',
    divider,
    chalk.dim(`  Generated by claude-onboard using claude-sonnet-4-6`),
    '',
  ].join('\n')

  return header + formatted + footer
}

export function formatAsMarkdown(guide, repoName) {
  return [
    `<!-- Generated by claude-onboard | ${new Date().toISOString()} -->`,
    `<!-- Repo: ${repoName} -->`,
    '',
    guide,
  ].join('\n')
}
